version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && rails s"
    environment:
      DB_HOST: postgres
      RAILS_ENV: production
    volumes:
      - .:/digging_manager
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgis/postgis:9.5-2.5-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
