inherit_from:
  - ../.rubocop.yml

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Exclude:
    - 'factories/**/*'

RSpec/EmptyLineAfterHook:
  Exclude:
    - 'factories/**/*'
    - 'support/**/*'

Style/BlockDelimiters:
  IgnoredMethods:
    - expect

RSpec/HookArgument:
  Exclude:
    - 'support/**/*'
